/* ═══════════════════════════════════════════════════════════════════════════
   currencyService.js — GEMS + HEARTS
   ---------------------------------------------------------------------------
   Every gem and every heart in LunX moves through this file. Components never
   do `setGems(gems + 20)`; they dispatch an action that lands here, so each
   transaction is validated, recorded in the ledger and impossible to run
   twice by accident.

   Hearts regenerate from a TIMESTAMP, never from a setInterval, so recovery
   keeps working while the tab is closed, the laptop is asleep, or the browser
   is quit entirely.
   ═══════════════════════════════════════════════════════════════════════════ */

import { HEARTS, HEART_RECOVERY_MS, MISC } from '../config/progressionConfig'

/* ── Ledger ──────────────────────────────────────────────────────────────── */

export function pushLedger(state, entry) {
  const ledger = [{ ts: Date.now(), ...entry }, ...state.ledger].slice(0, MISC.LEDGER_LIMIT)
  return { ...state, ledger }
}

/* ── Gems ────────────────────────────────────────────────────────────────── */

export function canAffordGems(state, amount) {
  return state.gems >= Math.max(0, Math.floor(amount))
}

/**
 * Award gems. Always returns a new state plus the events the UI animates.
 * Amount is floored and clamped at zero — a negative award is a bug, not a
 * spend, so it is ignored rather than silently draining the balance.
 */
export function awardGems(state, amount, reason = 'unknown', meta = {}) {
  const value = Math.max(0, Math.floor(amount))
  if (value === 0) return { state, events: [] }

  let next = {
    ...state,
    gems: state.gems + value,
    daily: { ...state.daily, gems: state.daily.gems + value },
    weekly: { ...state.weekly, gems: state.weekly.gems + value },
    stats: { ...state.stats, totalGemsEarned: state.stats.totalGemsEarned + value },
  }
  next = pushLedger(next, { kind: 'gems', amount: value, reason, ...meta })

  return {
    state: next,
    events: [{ type: 'GEMS_AWARDED', amount: value, reason, total: next.gems, ...meta }],
  }
}

/**
 * Spend gems. Refuses to take the balance negative and reports `ok: false`
 * so the caller can show "not enough gems" instead of guessing.
 */
export function spendGems(state, amount, reason = 'unknown', meta = {}) {
  const value = Math.max(0, Math.floor(amount))
  if (value === 0) return { state, events: [], ok: true }
  if (!canAffordGems(state, value)) {
    return {
      state,
      events: [{ type: 'GEMS_INSUFFICIENT', required: value, balance: state.gems, reason }],
      ok: false,
    }
  }

  let next = {
    ...state,
    gems: state.gems - value,
    stats: { ...state.stats, totalGemsSpent: state.stats.totalGemsSpent + value },
  }
  next = pushLedger(next, { kind: 'gems', amount: -value, reason, ...meta })

  return {
    state: next,
    events: [{ type: 'GEMS_SPENT', amount: value, reason, total: next.gems, ...meta }],
    ok: true,
  }
}

/* ── Hearts ──────────────────────────────────────────────────────────────────
   `heartAnchor` is the instant the current regeneration cycle began. While
   hearts are below maximum it counts up; when hearts hit maximum it is null.
   Recovery is therefore a pure function of (anchor, now) and survives the
   page being closed for a week.
   ─────────────────────────────────────────────────────────────────────────── */

/**
 * Apply however many hearts SHOULD have regenerated by `now`.
 * Call on load, on every tick and before any heart is spent.
 */
export function applyHeartRegen(state, now = Date.now()) {
  const max = state.maxHearts

  if (state.hearts >= max) {
    /* Full — make sure no stale anchor lingers. */
    return state.heartAnchor === null
      ? { state, events: [] }
      : { state: { ...state, heartAnchor: null }, events: [] }
  }

  /* Below max with no anchor (fresh install, migrated data, dev tools) —
     start the clock now rather than granting a windfall. */
  if (!Number.isFinite(state.heartAnchor)) {
    return { state: { ...state, heartAnchor: now }, events: [] }
  }

  const elapsed = now - state.heartAnchor
  if (elapsed < HEART_RECOVERY_MS) return { state, events: [] }

  const earned = Math.floor(elapsed / HEART_RECOVERY_MS)
  const hearts = Math.min(max, state.hearts + earned)
  const gained = hearts - state.hearts
  if (gained <= 0) return { state, events: [] }

  /* Carry the remainder forward so partial progress is never lost. */
  const anchor = hearts >= max ? null : state.heartAnchor + earned * HEART_RECOVERY_MS

  return {
    state: { ...state, hearts, heartAnchor: anchor },
    events: [{ type: 'HEARTS_RECOVERED', amount: gained, total: hearts }],
  }
}

/** Spend a heart (a wrong answer in a graded lesson). Never goes below zero. */
export function loseHeart(state, reason = 'mistake', now = Date.now()) {
  const regen = applyHeartRegen(state, now)
  const base = regen.state
  if (base.hearts <= 0) {
    return { state: base, events: [...regen.events, { type: 'HEARTS_EMPTY' }], ok: false }
  }

  const hearts = base.hearts - 1
  const next = {
    ...base,
    hearts,
    /* Starting from full begins a fresh recovery cycle. */
    heartAnchor: Number.isFinite(base.heartAnchor) ? base.heartAnchor : now,
    stats: { ...base.stats, totalHeartsLost: base.stats.totalHeartsLost + 1 },
  }

  const events = [...regen.events, { type: 'HEART_LOST', total: hearts, reason }]
  if (hearts === 0) events.push({ type: 'HEARTS_EMPTY' })

  return { state: next, events, ok: true }
}

/** Give back N hearts (rewards, dev panel, future shop items). */
export function restoreHeart(state, count = 1, reason = 'restore', now = Date.now()) {
  const regen = applyHeartRegen(state, now)
  const base = regen.state
  const hearts = Math.min(base.maxHearts, base.hearts + Math.max(1, Math.floor(count)))
  const gained = hearts - base.hearts
  if (gained <= 0) return { state: base, events: regen.events }

  return {
    state: {
      ...base,
      hearts,
      heartAnchor: hearts >= base.maxHearts ? null : (base.heartAnchor ?? now),
    },
    events: [...regen.events, { type: 'HEARTS_RESTORED', amount: gained, total: hearts, reason }],
  }
}

/** Refill to maximum. */
export function restoreAllHearts(state, reason = 'refill', now = Date.now()) {
  if (state.hearts >= state.maxHearts) return { state, events: [] }
  const gained = state.maxHearts - state.hearts
  return {
    state: { ...state, hearts: state.maxHearts, heartAnchor: null },
    events: [{ type: 'HEARTS_RESTORED', amount: gained, total: state.maxHearts, reason }],
  }
}

/** Buy a full refill with gems. Atomic: either both sides happen or neither. */
export function refillHeartsWithGems(state, now = Date.now()) {
  if (state.hearts >= state.maxHearts) {
    return { state, events: [{ type: 'HEARTS_ALREADY_FULL' }], ok: false }
  }
  const spend = spendGems(state, HEARTS.REFILL_GEM_COST, 'heart-refill')
  if (!spend.ok) return { state, events: spend.events, ok: false }

  const refill = restoreAllHearts(spend.state, 'gem-refill', now)
  return { state: refill.state, events: [...spend.events, ...refill.events], ok: true }
}

/** Can the learner open a graded lesson right now? */
export function canStartLesson(state, now = Date.now()) {
  const { state: fresh } = applyHeartRegen(state, now)
  return fresh.hearts >= HEARTS.COST_TO_START_LESSON
}

/**
 * Recovery timing for the hearts popover.
 * Everything is derived from the anchor, so reopening the page mid-cycle
 * shows the correct remaining time rather than restarting a countdown.
 */
export function getHeartRecoveryTime(state, now = Date.now()) {
  const max = state.maxHearts
  if (state.hearts >= max) {
    return { isFull: true, msUntilNext: 0, msUntilFull: 0, nextHeartAt: null, fullAt: null }
  }

  const anchor = Number.isFinite(state.heartAnchor) ? state.heartAnchor : now
  const elapsed = Math.max(0, now - anchor)
  const intoCycle = elapsed % HEART_RECOVERY_MS
  const msUntilNext = HEART_RECOVERY_MS - intoCycle
  const missing = max - state.hearts
  const msUntilFull = msUntilNext + (missing - 1) * HEART_RECOVERY_MS

  return {
    isFull: false,
    msUntilNext,
    msUntilFull,
    nextHeartAt: now + msUntilNext,
    fullAt: now + msUntilFull,
    cycleProgress: intoCycle / HEART_RECOVERY_MS,
  }
}

export default {
  awardGems, spendGems, canAffordGems,
  loseHeart, restoreHeart, restoreAllHearts, refillHeartsWithGems,
  applyHeartRegen, canStartLesson, getHeartRecoveryTime, pushLedger,
}
